language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'
  - '7.3'
  - '7.4'

matrix:
  fast_finish: true
  include:
    -
      php: '7.2'
      name: "Lowest dependencies"
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
